# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4464c50b21a3e535ab1fe1afbd42d6ca10fc28c6ef92ee7d5b8fb535cea19edd1b525989ba8cf27b79adb6f3d49f3693b2f575cb6b148c6d123f2463d5b203a1

test:
  secret_key_base: d50d409fef82fab0ea959892e126ae4a470f1f446a4e98ff4fc32cd6fb2f4b5312d14e6618cba0be6ae708b78dd9848de011d5d8090e9e766fc4d8b6f80c1e69

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
