# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89cb1b169d0ff58a1a4e3ac8d659a814d4b3f3ededb9194f6c448923a41fa07280e48071588610525bdfc818e66a094a36e3992e5c5c5d89bde4d09f66ab0139

test:
  secret_key_base: 5474e7553c9a49a242677de68c45a678c1c11a9d3c3a868af1c313db7b202dd39d60243b5e5ae2942e13d6c04b5ecae02f32634961e4d63c9146fa840e92ae8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
