# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec1e33ff4dd02ad6ac4b7ab7ab112d780491b9eb058d36682070ba3b9ec5ee9320a99b0e8bdd1b83ab49e33e71ac0d6d21e3470a4df6d166da67aa441db4d2c4

test:
  secret_key_base: 590ea464b0331e24f4f47de406db5bc23f60c745d8318e5190e000bafda48bd34dc755c5f1490ee004e5779d54e9b8fd85bc7c7dca721e9c877414dcdb98ed4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
