# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d1a1584e76ed54bdcf711ed3859db482cfb9d682fefbfd2b1979aa244c8d86ccb6bee234d7d8463f1f04257fad73ef33dfd07d37de5c79d5ae874db26b9c10c

test:
  secret_key_base: bbc3a5475885583cc5a91f467aa0f032c358ee26a6e336aab8ae851af6e046aadd5515b19b94efb8e9170d1d05907231276314800db975fe590aee84c7f226a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
