# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28843e25c639d28918679851049549347b965afc2e60b41ff1ab7aa89c80b9dca86c7335dbfea48e91e8c89af359b29ab243e3b480870f013969e4d4dc2b8f25

test:
  secret_key_base: d12e969d8e46803dd5e6fc093f923b9fb343143e9258ad46e1082c54d34160ae9ab5d15f2f46d19d65abc37285b8125f961b78bd173990d701a48b92258d9753

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
