# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00d10a9d04530446bf06560ce9e70fb4d5145e74badd57226a230eef48244bc379b61f036dbddc7c73123b8b4009319e319927e5346fb93ee6a00751b06c19e8

test:
  secret_key_base: dcf9a11054b9b44aed97bc8ef0f1f11e8356638080c4b24fc495036272e520d9c3d1af638ece4e843b1dbd5c4816d5c51924f62616476fa4fe5bde6c1c6196c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
